### ISSUE TITLE
egg 8x8 solve sub 600

### ISSUE THREAD

**Issue by eggyaytso** [benwh1/eggbot#14]
first solve in 3 months
3:14.855	593	3.043
2 30 13 4 24 54 32 60/42 5 21 51 40 18 31 62/29 25 6 19 50 0 57 48/1 46 20 3 37 15 28 38/43 45 23 27 53 7 12 35/8 22 49 34 61 17 26 10/41 52 16 63 14 33 44 55/58 9 59 36 11 39 47 56	URDR4U3L2URDRULURD2LUL2DRDLULU2R2DLDLD2LU3RDL3D2R2DLURDRU2LD2R2U2R3DLULDRDLDR2U2L3RLURDRUL2DUL2DR2U2LDR2UL3DR5UL3DR3UL2URDLU2RDLD2RDRU4L3DRDL3URD3LDRDRURULDRURDRULDLUL2DRDRDR2U2L2D2LUL2URD2LULURDLU2RULDLD3RURUL2D2RUR3URDL2DR2U3LULDRUL2ULD4RU2R2UL2UL2D2R2UL2D2RULD2RULDR2URULDRURURD2L2U2RURDRULDLURURD5LULDRULULD2RURUL3DR3UL2DRUR2D2LURULDLUR2DLU3RD2LU2RDLDL2URDRULD2LU4RDRD3L2U3L2DRURUR2D2L3DR2URDL3DR3UL2ULDLDR3ULUR2DL2UR2DLU2LURDLU2RDLDLDLDR2ULUL2DRDR2URDL4U2RDRULUR2DL2UR2DLU2RD2RU2L3DRDRULD2R2ULULDLURD2RUL3DR2UL2DR2URULUL2D2RURUL2D2RULUR2DL2UR2DL2U

**Comment by eggyaytso** [comment]
5x5 ao5 126
121
(152)
128
129
(114)

**Comment by eggyaytso** [comment]
6x6 ao5 248 (bad)
(215)
259
(274)
234
251 - i failed that one, could be ~240

**Comment by vovker2** [comment]
dph do you not have access to discord

**Comment by vovker2** [comment]
nice averages btw

**Comment by eggyaytso** [comment]
> dph do you not have access to discord

uhh should not use it
also egg . ... repl website is banned for me
can you send link for google?

also pls do movecount ranks list

**Comment by eggyaytso** [comment]
7.561	61	(8.067)	9 12 10 13/15 3 4 1/5 2 6 7/14 8 0 11	D3LURULDRDLU2RDRDLURURD2LU2LUR2DLURD2L3U2R2DLDRUL2URD2LURUL
9.199	53	5.761	9 0 11 15/5 3 7 6/4 1 14 12/10 2 13 8	U3LD3RU2RD2LU2RUL3DRDRDLULDR2U2RDL3URULDRDLU2RDLU
11.848	59	4.979	11 0 10 3/8 9 7 12/2 4 15 5/1 13 14 6	RU3L2DRDLULDR3UL2D2RU2LD2R2ULDL2URU2LDRDRULURDL2DR2U2LDLU
(7.279)	(52)	7.143	0 9 3 14/1 11 2 5/7 13 10 8/6 15 12 4	U2L3URDLD2RU2LDR2DL2URU2R2D2L2ULURDR2DLU2L2D2R2UL2U
12.704	54	4.250	6 12 15 3/8 0 14 2/13 1 9 5/10 11 7 4	UL2UR3DL2D2R2ULULD2R2UL3UR2D2LURDL2U3RDLDRURUL2DRUL
9.625	58	6.025	13 4 7 10/6 9 2 0/12 15 1 3/8 5 14 11	RURDLDRUL2DRU2LDRURURD3L2URURDLULUR2DL2URD2LULDR2ULULDRUL
7.800	52	6.666	0 8 2 14/13 6 15 5/9 1 3 4/12 11 10 7	LU2RDL3U2R3DLDLDR2UL2DRUL2DRU2LD2RU2LUR2DL2UR2DL2U
10.335	54	5.224	7 8 6 1/13 12 14 4/3 5 10 15/2 9 11 0	RD3LUR3U2LD2RULURDLULD2RDLULURDR2DLURUL3DR2U2L2DRUL
(20.040)	(79)	(3.942)	15 11 12 7/0 13 10 3/1 4 14 2/6 9 5 8	LURD2LU3RDL2URDLDLURD2R2UL3DRU2RD2LU2RDLDR2ULDLU2LDR2ULURDLDRU2LD2LU2RD2LURUL
15.664	62	3.958	9 13 3 5/15 6 8 2/7 10 0 11/14 1 4 12	URD2LU2RD3LU2RDL2DR2UL2URURDRD2LUL2UR3ULDRDL2U2RDL2DR2ULDLU2
13.904	70	5.034	9 12 0 3/11 4 13 6/2 5 10 7/14 15 8 1	LU3RD2RDLUR2UL3DRU2RD2L2DR2URDLU2RUL2D2RURDLULDLU2RDRDL2U2RDLUR2DL2U
10.368	62	5.979	7 6 5 3/12 1 9 4/0 11 14 15/2 8 10 13	UL2DR2D2LU2RD2LULDLU2R2UL2DR2ULDR2UL2DR2DL2UR2DL2ULDR2U2L2DRUL
				
10.900	58.500	5.501

**Comment by eggyaytso** [comment]
38.174	201	5.265	18 15 8 30 11 21/13 1 22 5 10 6/28 14 19 2 16 32/20 4 24 23 9 29/31 34 12 3 26 0/25 7 27 35 33 17	DR2UR2URDLULD2R2ULD2LURDRULDRDLULD2R2UL2DLULDLU3RDLDR2U3LDR2DRDL3DR2U2RD2LULURDLDRU2LDRUL2DRULULDR3URD2L4URULDR3UL2DR3UL2URDLDR2U2LDL2U2LDRUR3DL2DLDRULULD2RURUL2UR2DLDR2UL3DR3U2L2D2RUL2DRU2L

**Comment by eggyaytso** [comment]
33.509	93	2.775	3 0 4 5 8/1 18 6 23 2/12 10 19 14 24/7 22 15 16 20/11 21 9 13 17	RU4LDL2D2LUR3DL2UR3DL4DR3U3LDR2ULDLU2L2D2RDLUR2ULDRDLU3RDLDR2ULULDLDR2U2LDLDR2U2LDLU

**Comment by thelegendary08** [comment]
yoo dph
just wanted to let you know i'm alive and i just got ascended tier earlier today :))

**Comment by benwh1** [comment]
@eggyaytso pls don't beat me at fmc. I got 193 on the 6x6 and 95 on the 5x5

ai solutions:
6x6 143: D2RD2LUR2U3LURDRD2RUL4U2RDR3URD2LURD3LU2RDL2DRDRULDLULDLURDRUR2UL2ULD2RU2RD3LU2L2DRU2LULDRDLURUR2DLDLDLURU2R2DRU2L3DLDR3DR2U2L2URDLUL3
5x5 75: RU4LDL2ULD2RDLDR2U2RUL2DRU2LDLDR2DLUR2DLDRUL3UR2U2LDLDR4DLURUL2D2LU2LU

dawid finished 128x128 in 32:27:27.277 and 3 million moves, he had 63 cycles that took 5 hours to find

if websites are blocked, save them on https://archive.is/ or https://web.archive.org/ and look at them on there, e.g. https://archive.md/HRc5b

also everyone in the server says happy birthday 🥚

**Comment by eggyaytso** [comment]
thanks everyone ;)

Also pls do movecount ranks

**Comment by eggyaytso** [comment]
3x3	BLD	Standard	dphdmn	2.401	14.666	9.528	-	-	Average of 5	Keyboard	17 сен 2021, 18:26

3x3 bld ao5 movecount wr egg

**Comment by benwh1** [comment]
🥚

also are you not allowed to go on discord or can you not go on for some other reason

**Comment by eggyaytso** [comment]
3x3 ao100
3x3 ao50
3x3 ao12
3x3 ao5
4x4 ao100
4x4 ao50
4x4 ao12
4x4 ao5
5x5 ao50
5x5 ao12
5x5 ao5
5x5 single
6x6 ao12
6x6 ao5
6x6 single
7x7 single
8x8 single
9x9 single
10x10 single
categories for mvc

idk discord is edgy

**Comment by benwh1** [comment]
I will add moves categories at some point, maybe soon

should I try and make a page on slidysim.000webhostapp.com that you can use to send messages to the discord without having to log in

**Comment by eggyaytso** [comment]
@benwh1 

6x6 ao5 movecount WR 237
not very good last solve

(37.023)	(227)	(6.131)	21 2 27 1 15 7/3 11 13 6 14 22/5 30 16 24 20 12/26 8 25 4 10 9/19 28 35 32 29 31/0 33 18 17 34 23	L2D2RUL4DRDRU2LD3R3DL2UR3ULDRDL2UR2DL2U2RDL2UL2D2RUR2ULD2RUL3DR2ULUR3DL2URUL3URUR2DLDL2D2RURULDRUR2DRDL2UR2DL3ULUR2D2LU2R3UL2DR2ULURD2L2URUL2DL2DRU2RD2RDLULUR3DL2DR2UL2UL2DR2DL2UR2DL2U2R2DRDLU3RD2L3U2RD2LU2R2D2L2U2
43.456	243	5.591	5 28 2 13 33 22/1 14 27 10 18 12/26 34 30 15 35 20/11 25 0 7 23 32/16 29 3 31 21 8/9 17 6 19 4 24	ULUR2DL2UR3DL2UR2DLDRULD2LULULURDL2DRDRU2LD3RU2RU2L2DLURD4RDLULDR5ULDL2U2RDRDLULULD2R2UL2DR2UL2ULDRURURDLDR2UL2DR3UL2DR2ULU2L2ULDRDRDRU2LULDRD3RU4LD4RU2LDL2DR3U2L3D2RU2LU2RDRDL2UR3DL3DRURDLU2RDLU2LDLD2R2U3RD2L3UR2ULDRDL2URUL
45.328	231	5.096	7 25 16 17 30 6/26 31 5 24 21 18/1 4 34 2 10 28/8 35 11 29 15 33/27 13 19 9 23 20/0 22 14 32 12 3	DL4ULD2RU2LD4RU3RDLD2RU2RDRDRULD2RULDLULDRU2RU2RD3LU3RD2LU3RD3LD2LU2LDRULDLDR2UL2U2RD2LU2LD2RURUR2DLU3RD4LU2RD2LULURU2L2DR3UL2DRULDR2DLDRULDLULDUDLURULDR3UL2DR2URDL2URUL3DRD2RU2RD2LU3LDR2ULDRDL2U2RDRDL2U2RDL2DR2UL2U
50.800	237	4.665	22 17 14 28 6 8/32 2 15 12 24 11/10 25 13 34 18 1/29 19 26 33 5 27/21 9 16 35 30 7/0 20 31 4 3 23	L2DR2ULDRDLDRULDL4DRU4RD2LU2RDL2D4RU3RURDLD3LURULDRURULDRD2LU2RDRDLUR2DL3U4LDRURDLDRURURD2LDRUL2DRURDL2UL2DLU2R2D2LULURDLDRU2RDRDL2U2RDRULDR2DL2U2RDRUL2DRU2RD2LU2LUR2DLDL2DR2UL2DR2U2LURD2LU2LDLD2R2URUL2DR2ULDLULUR2DL2UR2D2LU2L
(53.871)	(250)	(4.640)	30 10 13 11 7 15/14 2 31 9 27 32/20 29 0 23 6 18/33 21 5 3 16 22/34 35 1 12 17 8/25 4 24 19 26 28	U3RDLUL2DRDLULD3RU3LD3RDLU2RDR2U3LD4RU4LD4RURDLU3RD2RDL2U3LURDRULURDLDR2ULDRU2L4DRD2LD2R2ULULUR2DRDL2ULDRUR3DL4UR4DL4U2R3DL2DLURDL2URDRU2L2URDRULURDR2UL3DR3UL2DRULD2R2DL4U2R2D2LULUR3DLURD2LULDRULU2RDLDRUL2DRU2LDRURDLULDRUL
				
46.528	237	5.117		
3.115

**Comment by eggyaytso** [comment]
also why eff have two strings in ao50 4x4 time pbs

**Comment by thelegendary08** [comment]
egg dph breaking wrs in army

**Comment by eggyaytso** [comment]
6x6 sub 200 pb
57.530	199	3.459	31 20 14 19 16 10/4 1 17 34 9 6/2 3 8 13 12 5/25 7 35 18 27 21/23 11 24 32 28 29/15 33 0 26 22 30	LDLDR2DLDL2DRULURDLDRU2R2D2RURDLU2RUL2D3RU2L2D2R2UL2U2R2D2LUR2DL2U2R2DLU3RD4LU4RD4LUL2DR2UL3DR2UL2DLU2RD2RU2LDR3UL2DR2ULURUL2DR2ULDLDRULD2RULDL2U2R2DLDRU2RDL2UR2UL2DR2DLU2LDLDR2UL2UR3DLUL2

**Comment by eggyaytso** [comment]
5x5 ao12 pb 135.2

**Comment by benwh1** [comment]
@eggyaytso should I try and make a page on slidysim.000webhostapp.com that you can use to send messages to the discord without having to log in

**Comment by eggyaytso** [comment]
> @eggyaytso should I try and make a page on slidysim.000webhostapp.com that you can use to send messages to the discord without having to log in

no ty

**Comment by benwh1** [comment]
@eggyaytso why not, it's annoying to only be able to talk on a github issue for the next 9 months

**Comment by benwh1** [comment]
> also why eff have two strings in ao50 4x4 time pbs

fixed
