### ISSUE TITLE
optional parameters for getpb and getreq

### ISSUE THREAD

**Issue by benwh1** [benwh1/eggbot#23]
default size parameter should be the channel (if 3x3-10x10) or 4x4 otherwise

default username parameter in getpb should be the users linked slidysim username

default tier parameter in getreq should be the next tier above the users current tier (or maybe the next tier above their pb for the puzzle? but maybe not because there can be multiple)

**Comment by eggyaytso** [comment]
> default tier parameter in getreq should be the next tier above the users current tier (or maybe the next tier above their pb for the puzzle? but maybe not because there can be multiple)
it can show next tier above pb for each category (single/ao5)... and it can be a new command actually

**Comment by benwh1** [comment]
>  it can show next tier above pb for each category (single/ao5)... and it can be a new command actually

yeah I guess that is possible. doesn't need to be a new command though

**Comment by benwh1** [comment]
default username in getpb: d80e08c24a4efc409264d26fd287425a322009a7

**Comment by benwh1** [comment]
default size parameters: d41212d9b43dfed4afc8edeb32bfc266198c78cd 7cda77cd3eb0ec2ef21e216ad24a8881f3f00d69

**Comment by benwh1** [comment]
show requirements for next tier above users pbs in !getpb (so we don't need default parameter in getreq now): 5181ef2380ee1039440514471fb1bb0326e87d9c
