### ISSUE TITLE
Happy Egg Day!

### ISSUE THREAD

**Issue by eggyaytso** [benwh1/eggbot#30]
Сегодня пятница, 8 октября.
Всемирный день яйца — праздник всех любителей яиц, омлетов, запеканок и глазуньи.

Ничего удивительного в этом нет. Ведь яйца — самый универсальный продукт питания, они популярны в кулинарии всех стран и культур, во многом благодаря тому, что их употребление может быть самым разнообразным.

История праздника началась в 1996 году на Международной яичной конференции в Вене, на которой было объявлено, что праздновать всемирный «яичный» праздник будут во вторую пятницу октября.

**Comment by thelegendary08** [comment]
<img width="227" alt="happy egg day" src="https://user-images.githubusercontent.com/83528176/136647775-3e2b58dd-1ff5-4418-9544-346517722087.png">

**Comment by benwh1** [comment]
![egg](https://i.imgur.com/wniCDMY.png)

**Comment by effperm** [comment]
yay
