### ISSUE TITLE
pls fix list of uwr on speedsolving wiki

### ISSUE THREAD

**Issue by eggyaytso** [benwh1/eggbot#34]
just look what frozen cuber did with the leaderboard
https://www.speedsolving.com/wiki/index.php/List_of_Unofficial_World_Records
>random moves scrambles
>all world records in sliding puzzles
mhm ok

**Comment by eggyaytso** [comment]
btw i am playing ms since september and also started playing vsrg

my best etterna score so far https://etternaonline.com/score/view/S70ed483653263867b7444c20d1afc7abb177f26b47284
ms: https://minesweeper.online/ru/game/968758998 (27.xx int)

________
why are there not much pbs at slidysim and spreadsheet updates guys???????????????

**Comment by thelegendary08** [comment]
im grinding slidysim every day but not getting new tiers (getting some small pbs tho)
