### ISSUE TITLE
ben please help

### ISSUE THREAD

**Issue by eggyaytso** [benwh1/eggbot#35]
hi @benwh1 ben can you help me with some math?
i'm making some recusion notation here, and then trying to get beyond that using Omega, then i made multiplication rules, but exponentiation is just a mess, what do i do

i just can't understand how to use those polynomials in W, the idea is that you use the rightest element of the polynomail, but i can't define it as general for any types of polynomails, it took me 2 hours to understand just kw+d case, i have no idea how to define anything bigger

question is: how to define exponentiation of W properly here?

[a, b, c], where a, b, c >= 0 (Z)

Rules:
Rule 1: [0, b, c] => b + c
Rule 2: [a, 1, c] => [a-1, c, c], (a>0)
Rule 3: [a, b, c] => [a, b-1, [a-1, c, c]], (a>0, b>1)

omega is a specical letter that is defined by such rules as:
Omega rule 1: [w, 1, c] = [c, c, c]
Omega rule 2: [w, b, c] = [w, b-1, [c, c, c]]

Multiplication and addition defined for W:
Omega rule 3: [kw, b, c] = [(k-1)w + c, b, c], (k>1)
Omega rule 4: [kw + d, b, c] = [kw+d, b-1, [kw+d-1, c, c]], (d>0, b>1, k>0)
Omega rule 5: [kw + d, 1, c] = [kw+d-1, c, c], (d>0, k>0)

exponentiation step i'm trying to define:
[w^n, b, c] = [w^(n-1) * c, b, c], (n>1)  //decreasing n rule
[w^n * d, b, c] = [(d-1)w^n + w^n, b, c]  //decreasing d rule
...?  [w^2, 1, c] will be [wc, 1, c] i guess

example:
[2w+1, 1, 2] = [2w, 2, 2] =  [w+2, 2, 2] = [w+2, 1, [w+1, 2, 2]] = [w+2, 1, [w+1, 1, [w, 2, 2]]] = [w+2, 1, [w+1, 1, [w, 1, [2,2,2]]]] =  [w+2, 1, [w+1, 1, [w, 1, [2,1,[1,2,2]]]]]=[w+2, 1, [w+1, 1, [w, 1, [2,1,[1,1,[0,2,2]]]]]] = [w+2, 1, [w+1, 1, [w, 1, [2,1,[1,1,4]]]]] = [w+2, 1, [w+1, 1, [w, 1, [2,1,8]]]] = ... =  [w+2, 1, [w+1, 1, [w, 1, 2048]]] =  [w+2, 1, [w+1, 1, [2048, 2048, 2048]]] = ... long thing = ... some number eventually

**Comment by benwh1** [comment]
are you just trying to define it to be something which is > everything that came before? e.g. https://en.wikipedia.org/wiki/Fast-growing_hierarchy#Definition. thats a sequence of functions with f(a+1, n) = f(a, f(a, f(a, ..., f(a, n)...))) nested n times, and f(w, n) is defined as f(n, n)

so maybe you could just define [w^n, 0, c] = [w^(n-1), c, c]? then e.g. [w^4 + 3w^3 + w, 0, c] would be [w^4 + 3w^3, c, c] => [w^4 + 3w^3, 0, d] = [w^4 + 2w^3, d, d] => ...etc. where you are using [a, b, c] = [a, b-1, [a-1, c, c]] to get from [something, c, c] to [something, 0, d]

**Comment by eggyaytso** [comment]
@benwh1 
actually it is my attempt to understand it using strong rules and array notation

> [w^4 + 3w^3 + w, 0, c] would be [w^4 + 3w^3, c, c]

not exactly, 2nd value can't be 0, let it be 1, but anyway, as i understand it:
[w^4 + 3w^3 + w, 1, c]  = [w^4 + 3w^3 + c, 1, c] = [w^4 + 3w^3 + c-1, c, c]... and then eliminating that [c-1] even more using generaliazation of "omega rule 4 and 5, until you end up with something like [w^4 + 3w^3, X, Y]
after that 
w^4 + 3w^3 = w^4 + w^3 + w^3 + w^3 = w^4 + w^3 + w^3 + w^2 * w, and at this step use rules "4/5" to get  w^4 + w^3 + w^3 + w^2 * **c**, or something like that

**Comment by eggyaytso** [comment]
@benwh1 
so the major problem is defining that i need the very "right" element of the polynomial of kw^n + kw^n-1...

**Comment by benwh1** [comment]
maybe look at this? https://en.wikipedia.org/wiki/Ordinal_arithmetic#Cantor_normal_form

also if you are using ordinals then technically you should write e.g. w^3 * 3 and not 3 * w^3 because they aren't the same thing, but never mind.

**Comment by eggyaytso** [comment]
@benwh1 i mean something like this https://en.wikipedia.org/wiki/Ordinal_arithmetic#Cantor_normal_form

**Comment by eggyaytso** [comment]
@benwh1 ??????????? yes just reading this link

**Comment by benwh1** [comment]
so maybe I would define [a, 1, c] like this:

- write a = w^b1 + w^b2 + ... + w^bk with b1 >= b2 >= ... >= bk
- if bk is not a limit ordinal, define [a, 1, c] = [w^b1 + ... + w^(b(k-1)), c, c]
- otherwise if bk is a limit ordinal, write bk = w^c1 + ... + w^cn
- if cn is not a limit ordinal, define [a, 1, c] = [w^b1 + ... + w^(w^c1 + ... + w^(c(n-1)), c, c]
- otherwise, write cn = w^d1 + ... etc repeating until you get to something which isn't a limit ordinal

this works for defining [a, b, c] for all а < epsilon_0 (= w^w^w^w^...)

**Comment by eggyaytso** [comment]
@benwh1 
https://www.sites.google.com/site/largenumbers/home/4-2/fgh_ww
just found this

**Comment by benwh1** [comment]
ok, looks pretty much like what I was thinking of when I wrote the last comment

**Comment by eggyaytso** [comment]
anyway, using polynomials looks ugly, why would we use that, there must be a better way of getting 1 step further
