### ISSUE TITLE
happy new egg! (pls help)

### ISSUE THREAD

**Issue by eggyaytso** [benwh1/eggbot#37]
someone pls reupload slidysim exe and binary on github so i can download it, i can't get access to links on the main website

**Comment by sqmasep** [comment]
happy new egg dph!

**Comment by benwh1** [comment]
do you mean you can't get to the website? or you can get to the website but you can't get to mediafire?

**Comment by eggyaytso** [comment]
can't get to mediafire, also any other cloud websites like google drive

**Comment by benwh1** [comment]
> can't get to mediafire, also any other cloud websites like google drive

can you get to https://www.file.io/

**Comment by eggyaytso** [comment]
works i guess

**Comment by benwh1** [comment]
windows or linux?

**Comment by eggyaytso** [comment]
win

**Comment by benwh1** [comment]
> win

https://file.io/dxqW1ZC4f8kH

**Comment by eggyaytso** [comment]
not working :(

**Comment by benwh1** [comment]
blocked again?

**Comment by eggyaytso** [comment]
yes
i know that github still works

**Comment by benwh1** [comment]
> yes i know that github still works

https://github.com/benwh1/yaytso

**Comment by eggyaytso** [comment]
here we go
thanks!
