### ISSUE TITLE
20x22 WR for 2022 :)

### ISSUE THREAD

**Issue by eggyaytso** [benwh1/eggbot#38]
![Безымянный](https://user-images.githubusercontent.com/90030386/147833618-4a3d1b44-854c-49ba-82fe-f6bb2925c640.png)
20x22	Standard	Standard	dphdmn	23:37.285	20287	14.313

**Comment by benwh1** [comment]
![solve](https://i.imgur.com/Me9DF3Y.png)

![egg](https://i.imgur.com/wniCDMY.png)
