### ISSUE TITLE
leaderboard and webiste are dead, still

### ISSUE THREAD

**Issue by eggyaytso** [benwh1/eggbot#44]
ben fix pls

**Comment by eggyaytso** [comment]
also 21.6xx something ao50 on 3x3 movecount pb with like 20.0x something average optimal, very dumb mistakes at the end :(

**Comment by benwh1** [comment]
yes i know, i already emailed them about it but they havent responded yet

**Comment by eggyaytso** [comment]
bruh it's been a week, still nothing :(

**Comment by eggyaytso** [comment]
"Website is no longer available
The authors have deleted this site."
ben pls
