### ISSUE TITLE
some more funny stats // when website is back???

### ISSUE THREAD

**Issue by eggyaytso** [benwh1/eggbot#46]
hey it's march and i'm still alive

ao50: 3.823	72.916	19.378
decent movecount with "high" tps

also, interesting scramble:
3 0 6 7/1 5 15 4/13 2 10 11/14 9 12 8

**Comment by benwh1** [comment]
that's good. have you been sent to ukraine yet

that scramble is one of those that's almost really easy but there are 3 or 4 pieces that are the wrong way around that make it less easy

vovker rejoined the server 2 weeks ago and switched to keyboard 🥚

idk when website back. they still haven't responded

**Comment by eggyaytso** [comment]
> idk when website back. they still haven't responded

@benwh1 please do something, it's just saying that there is no website at all anymore, can you just reupload the last backup of it as a new copy with same addres?
i don't think they will respond, because you are using free account so nobody cares

**Comment by eggyaytso** [comment]
#learning-english-every-day
tried to read some english book
8 pages in 1 hour
~130 words i don't know
omg
how can there be that many weird words
![wordcloud](https://user-images.githubusercontent.com/90030386/157064135-a2468224-866b-4acb-bc6d-447c55a85d99.png)
upd: i know what clouds is, it was "clouds brewing overhead" phrase, uh, whatever, same with "someone", "high" and some other words

**Comment by thelegendary08** [comment]
to help you with some words
troops - like forces of the army, each unit is a troop
shivering - its the thing you do when you're cold to generate heat
gloat - boast
nonetheless - nevertheless
eagle - a type of bird, carnivorous maybe (only eats meat)
trembling - shivering in fear 
debris - kind of like fragments, small pieces of rubbish from an explosion or smth usually
slain - killed

cant be bothered to do more eg

**Comment by eggyaytso** [comment]
@thelegendary08 
i have translation of all the words
but i gave up on checking them after first chapter of the book because it's just annoying and i need the access to internet while reading to do that quickly
maybe i'll do that later

**Comment by eggyaytso** [comment]
failed pb scramble :/
missmoved 1.7
1.727	32	18.529	1 2 0 4/9 6 5 11/10 8 15 3/13 14 7 12
[1.072 / 28] second try
[0.775/28/36.129] after some attempts
not sure what's the potential of that scramble, i wish i had a tablet

**Comment by eggyaytso** [comment]
some things:
4.529 ao50 with 71.687 movecount
20.821 movecount ao30 on 3x3 (failed after that)
first 4x4 x10 marathon in like 8 months: 40.271 (719/17.854)
187 moves 5-2 relay (100/66/20/1) idk what was the leaderboard

**Comment by eggyaytso** [comment]
yet another sub 59 moves ao12 with shit ending :(
```
(6.879)	(38)	5.524	5 2 7 4/3 9 12 0/10 6 15 11/1 13 8 14	UR3ULDLULDR2DRDLURUL2D2R2UL3URDRU2L2	15 мар 2022, 12:49
7.183	48	(6.682)	0 13 2 9/5 10 3 4/6 1 7 8/15 12 14 11	LU2RDLDRULDLU2RD2L2URDRURUL2DRULUR2DL2DLU2R2DL2U	15 мар 2022, 12:49
10.223	64	6.260	15 11 4 7/1 2 9 5/8 3 0 13/6 12 10 14	DRUL2D2RURDRULDLUR2UL3DR3UL3DR2ULUR2D2LU2LDLDR2U2L2DR2UL2DRUL	15 мар 2022, 12:49
11.863	53	4.467	6 10 5 8/1 2 15 7/14 13 4 3/0 9 11 12	LDRULDLDRDLURDRUL3UR2D2L2URULDRDLURULURD2LURULD2RU2L	15 мар 2022, 12:49
12.455	52	4.175	12 1 4 6/13 14 9 5/0 2 10 3/8 11 15 7	DLU2RD3LUL2U2R2DRDL3DRULU2R2DL2UR2DRDL3UR2UL2DRUL	15 мар 2022, 12:50
20.255	69	3.406	8 7 5 14/2 1 0 4/11 13 6 10/12 15 9 3	DR2UL2DR2UL2U2R2DL3UR3DLDL2DRULURDLDRULU2RDRUL2D2RURULDLUR2DLULDRUL	15 мар 2022, 12:50
11.183	63	5.633	8 11 2 14/15 6 0 3/4 9 1 10/13 5 12 7	R2UL2DRU2LD3R2ULULD2R2UL2U2RD2LDRUL2DRULU2R2DLDRUL2DRULUR2DLUL	15 мар 2022, 12:51
10.135	61	6.018	10 3 2 6/9 1 11 14/13 12 7 5/0 8 15 4	LDL2UR3D2L2URDLDR2UL3DR2UL2U2R2D2LDLU2RDLU2R2DL2URD2LU2RDLU	15 мар 2022, 12:51
11.943	60	5.023	13 10 7 15/4 6 1 11/9 14 0 2/5 8 3 12	URD2LDRURDLURU2LD2RULDLULDRU2R2DLDLDRUL2DRU3LD2RU2LDR2DLU2L	15 мар 2022, 12:51
12.903	57	4.417	11 3 8 5/12 15 4 14/6 1 7 9/0 13 2 10	L2DLDRDLUR3UL2DR2ULUL2DRDRULD2RULDR2ULDLU2RUL2DR2DLURUL2	15 мар 2022, 12:51
(30.446)	(76)	(2.496)	14 1 9 12/3 7 5 10/15 2 13 8/11 4 6 0	R2DLURDRULD2RDL2U3LD3RU2LD2RURDLULU2RDR2DL2UR2DL3URURDLULDRURDLDRU2L2DRUL	15 мар 2022, 12:52
16.415	62	3.777	3 8 0 15/10 4 12 9/13 1 6 5/11 2 14 7	RU3RD2L2DR2ULUL2D2R2U2L2DR3UL2DR2ULDLU2LDRURD2LULURDRUL2DRUL	15 мар 2022, 12:53
					
12.455	58.900	4.870			
3.422					
```

//64.8 ao68

**Comment by benwh1** [comment]
@eggyaytso good

also website is gone, apparently it is permanently deleted after 2 weeks. so i will have to get a new web server and update the sim sometime

**Comment by eggyaytso** [comment]
> @eggyaytso good
> 
> also website is gone, apparently it is permanently deleted after 2 weeks. so i will have to get a new web server and update the sim sometime

nice.
meanwhile i have sub 65 ao75 session and can't finish it because have no time :(

**Comment by benwh1** [comment]
@eggyaytso apparently 2-5 moves leaderboard was vovker 179, me 181, then 187 is 3rd. I just got 171 though (96 62 12 1, saved by 3x3 🥚)

**Comment by eggyaytso** [comment]
@benwh1
190 with 130 and 33
```
5x5: 22.328, 130 moves, 5.822tps
4x4: 6.446, 33 moves, 5.119tps
3x3: 8.400, 25 moves, 2.976tps
2x2: 0.864, 2 moves, 2.314tps
5x5: 0 20 19 7 9/17 1 23 5 12/16 18 13 15 10/24 11 2 4 3/21 14 8 22 6
4x4: 1 0 2 12/9 14 4 3/7 11 8 10/13 5 6 15
3x3: 8 3 6/5 2 1/7 0 4
2x2: 0 2/1 3
```

**Comment by eggyaytso** [comment]
@benwh1 pb 183 with 5x5 pb [92, 73, 16, 2] rip 4x4 :(
```
5x5: 14 1 12 5 15/10 22 9 3 7/17 16 8 4 20/2 6 11 19 24/13 23 21 18 0
4x4: 11 14 10 9/8 4 3 5/1 13 6 12/2 7 0 15
3x3: 2 5 6/1 3 8/0 7 4
5x5: D4RU2RD2LU2R3UL2DR2DLURD2LURU2L2URDLDRDRU2LURDLD2LU2RDL2DRUL2DR2ULDRU3RD3L2U2RULD2RU2L2
4x4: LD3RURDLULDR2URU2LD2RDLURULDRDLULUR2UL2DLDRUR2DL3UR3DL2U2RD2L2URDRUL2U
3x3: L2D2RU2LD2R2UL2U
```

ugly 4x4, can't save more than 4 moves after few retries
90 moves 5x5 second try

**Comment by eggyaytso** [comment]
6x6 N-2 relays:
475 [218, 156, 73, 23, 5] good 6x6 but many missmoves
469 [239, 150, 52, 26, 2] lucky 4x4
459 [246, 126, 62, 20, 5] lucky 5x5
i guess my limit here would be about 430 moves 

upd: 452 [225, 146, 60, 20, 1]
