### ISSUE TITLE
decent 7x7 solve

### ISSUE THREAD

**Issue by eggyaytso** [benwh1/eggbot#48]
378
18 25 13 43 4 5 6/1 23 10 8 24 46 7/9 22 47 44 48 42 28/2 36 15 12 19 29 31/38 35 0 32 27 41 37/16 11 20 30 33 34 3/45 39 26 21 40 14 17	UL3URD2LULDR2DL2UR2ULDRURD2LULD2LURD2R2DL3U2R2URD2RUL2DR3DRU3L2DL2DR2UR2DL2DRU2L3DR2DRURUL4DRUL2DRURULDRDRULDRU2LUR3D2LULD2R2U2L2URDRULURD2LU3RD4L3UR2DLDLU2RDLULD2RURUL2URD2RU2LDLULULUR2DL2D2RU2LD2RUR2DR2ULD2RULU2RDL2ULDR2ULUR2DLD2LU2LDRD2LUL2DR2ULUR2DL2UR2LDR2DL3ULDR2UR2DLULULDLU2R3ULDR2D2L3URUR2D2L2ULUR3D2L2ULDR2U2LURD2LU2LD2RU2LDR2UL3D2RU2LDR3UL2DLUR2DLUL
don't know if that is my slidysim pb, scramble is really lucky 
have better solve of tapsss i guess, meh

**Comment by benwh1** [comment]
apparently your slidysim pb is 385

**Comment by eggyaytso** [comment]
lemme recall my pbs for singles...
3x3 - 1
4x4 - at least 29
5x5 - 92 [16.03.2022]
6x6 - 199 [22.09.2021]
7x7 - 366 (phone) / 378 (slidy)
8x8 - 593 [15.09.2021]
9x9 - probably something 8xx in september 2021, at least 900?
10x10 - 1421 [20.05.2021]

**Comment by ghost** [comment]
from my knowledge

4x4 - 29
9x9 - 1034 (mobile) / 1139 (slidy)

if you got a 9x9 pb in september you didn't post it anywhere (or i missed it)

**Comment by eggyaytso** [comment]
@Daanbe i should have
and i uploaded it in lb

**Comment by ghost** [comment]
@eggyaytso if only one could see the lb 😔

**Comment by eggyaytso** [comment]
@Daanbe 
984 with cycle 9x9

upd:
970 [275, 503, 691 (279)] (9x9 8x8 7x7 (6x6) splits)

**Comment by eggyaytso** [comment]
6x6 1-move to pb solve, meh
32.510	200	6.151	7 29 1 15 10 22/11 12 2 0 4 23/33 35 8 13 32 27/25 3 9 21 18 6/19 31 5 26 30 20/28 16 17 34 14 24	UR2ULDRD2LU2RDRDL2ULURDRULUR2ULDLU2R2D3LURUL4URDLD2LU2RD2RD2LU2LDRUR2ULDRDLDLU2RDLULD2RULUR3DLULDRUR2DLU2RUL3DLURDR3UL3DR3UL2UR2DLD2RU2LD2LU3RD2LULD2LURDRU2L2UR2DRULDLDR2UL2DLUR2DLURUL2DR2UL2

**Comment by eggyaytso** [comment]
4x4 ao23 61.9
completely lost focus after few solves

**Comment by eggyaytso** [comment]
btw speedsolves:
4x4 3.586 ao28 / 75.269

ao5:
```
3.351	69	20.590
2.487	(48)	(19.300)
(3.375)	(71)	21.037
2.800	57	20.357
(2.240)	51	(22.767)
		
2.879	59	20.661
0.357		
```

**Comment by eggyaytso** [comment]
huge 6x6 pb fail
1 17 28 11 9 12/7 8 13 3 10 22/33 5 26 2 18 20/19 23 27 15 25 21/35 32 29 14 0 24/4 6 34 30 31 16	
URDLDR2UL2DR3UL2UR3DL2UR2DLDLU2RD3L2DRU2RD3LU4RD4LU2LD2RU3L2D3R2U2LDR2URDLULDR2ULU2L2DRURDLDL3D2R2U2LDR2UL2DR3UL2DLURDRULDLU3RDL2U2R2DL2D2R2U2LDRURD2LULUR2DL3U2R3D2L2U2RDLULDR2UL2DR2DR2UL2D2RU2RD2L2U3RD2L2UR2UL2D2RUL2UR2DLULDR2UL2
194 cycled

190 2nd attempt:
UR2DL2DR2UL2UR3DL2UR3DL2UR2DL3UR2D2LDR2DL2URDRULUL2U2LD5RU4LD4RU3LD2R2DL2URURDRDL2U2L2D2RURU2LD2RURUL2DR2URD2LURUL2UR2DL4DR3UL2ULUR2DRDLDLULURDLDRURDLU2RDLU2R2DL2URD2L2URDRUL2U

**Comment by eggyaytso** [comment]
just ao12 mouse pb 
3.273	71.700	21.868
not really good at that :/

**Comment by eggyaytso** [comment]
3x3 bld for fun 2.579 ao12
idk what is wr, 2 years ago i had like 2.8 pb with very low success rate
now i can do it without thinking, just have to track the number 5, i still can lose in like 1/7 games or so, but speed and compexety of the puzzle is not really matter anymore 
(keyboard)

upd: ah, gottogitgud has 2.086 ao50 bld, no questions anymore lol
i guess i have even better stats for this on mouse, can't remember at this point...
```
2.579 [0.589]	22.800	11.675

(1.759 [0.591])	(13)	11.130
2.575 [0.591]	21	10.584
2.071 [0.487]	20	12.626
2.639 [0.568]	21	10.140
2.575 [0.799]	24	13.513
2.559 [0.511]	22	10.742
2.935 [0.680]	27	11.973
(3.655 [0.631])	29	(9.589)
3.544 [0.544]	(37)	12.333
2.839 [0.559]	28	12.280
1.871 [0.647]	14	11.437
2.191 [0.575]	22	(13.613)
```

**Comment by eggyaytso** [comment]
4x4 bld succ
idk if this is a pb or not lol
6.183 [0.719]	48	8.784	2 4 11 15/1 0 7 12/8 3 9 14/13 10 6 5	UL2URDLD2R2U2L2D2R3ULURDL2URUL2D2RU2RDL2DR2U2L2

**Comment by eggyaytso** [comment]
3x3 bld got ao~28
